server:
  port: 8000
spring:
  application:
    name: platform-transaction
  profiles:
    active: micro-dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        username: nacos
        password: nacos
        shared-configs:
          - dataId: common-actuator.yml
            group: DEFAULT_GROUP
            refresh: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_service?characterEncoding=UTF-8&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=300&prepStmtCacheSqlLimit=2048
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

# tkmapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  identity: MYSQL
#  style: normal

# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  row-bounds-with-count: true
  support-methods-arguments: true

# mybatis
mybatis:
  mapper-locations: classpath:com.mservice.transaction.mapper/*.xml
  type-aliases-package: com.mservice.transaction.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true



