server:
  port: 8000
spring:
  application:
    name: platform-gateway
  profiles:
    active: micro-dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        username: nacos
        password: nacos


