server:
  port: 8001
spring:
  application:
    name: platform-transaction
  profiles:
    active: micro-dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        enabled: true
        shared-configs:
          - dataId: common-actuator.yml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_service
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #cpu_core*2+磁盘数 = 4*2+7=
      maximum-pool-size: 16
      #db_wait_timeout-30s
      max-lifetime: 86370000
#  data:
#    mongodb:
#      uri: mongodb://root:123456@127.0.0.1:27017/dev

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_empty
#  mapper-locations: classpath:com.mservice.transaction.mapper/*.xml
#  type-aliases-package: com.mservice.transaction.model
  type-enums-package: com.mservice.transaction.enums


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
  group-configs:

logging:
  level:
    com.baomidou.mybatisplus.samples: debug
    com.mservice.transaction: debug
#    root: debug

aliyun:
  accessKey: LTAI4GFVcfLsCuZn856kcEx4
  secret: JEzY5cbyRxJQuutFZIgtnIjlnD1pHj
  rock:
  tcpRocket:
    enable: true
    endpoint: http://1392465674862244.mqrest.cn-qingdao-public.aliyuncs.com
    instanceId: MQ_INST_1392465674862244_BXaVUfMQ
    nameSrvAddr: 1322
    sendMsgTimeoutMillis: 1000

my:
  i18n:
    enabled: false
  http:
    enabled: true
    retry: false
    connectTimeout: 15s
    readTimeout: 15s
    writeTimeout: 15s
    pool:
      maxIdleConnections: 5
      keepAliveDuration: 5m
    proxy:
      enabled: false
      host: 127.0.0.1
      port: 1087
      type: HTTP