server:
  port: 8001
spring:
  application:
    name: platform-transaction
  profiles:
    active: micro-dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        username: nacos
        password: nacos
        shared-configs:
          - dataId: common-actuator.yml
            group: DEFAULT_GROUP
            refresh: true
        enabled: false
      discovery:
        enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_service
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #cpu_core*2+磁盘数 = 4*2+7=
      maximum-pool-size: 16
      #db_wait_timeout-30s
      max-lifetime: 86370000


mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_empty
#  mapper-locations: classpath:com.mservice.transaction.mapper/*.xml
#  type-aliases-package: com.mservice.transaction.model
  type-enums-package: com.mservice.transaction.enums


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
  group-configs:

logging:
  level:
    com.baomidou.mybatisplus.samples: debug
    com.mservice.transaction: debug
#    root: debug

aliyun:
  tcpRocket:
    enable: true
    nameSrvAddr: 1322
    sendMsgTimeoutMillis: 1000

